name: 'demo_data'

version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'databricks'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

models:

  demo_data:

    # configure variables for use in models
    suspected_personas: 5

    +materialized: table

    staging:
      +docs:
        node_color: "CadetBlue"

    marts:
      +docs:
        node_color: "MediumSlateBlue"
    
    metrics:
      +docs:
        node_color: "Maroon"

    challenges:
      +cluster_id: "{{ env_var('DBT_DATABRICKS_CLUSTER_ID') }}"
      +submission_method: all_purpose_cluster
      
      +docs:
        node_color: "Violet"
      basics:
        +docs:
          node_color: "Indigo"
      ml:
        +docs:
          node_color: "Orchid"

tests:
  +docs:
    node_color: "black"

vars:
  truncate_timespan_to: "{{ dbt.current_timestamp() }}"
  s3_bucket: "s3://sales-sandbox-databricks-unity-catalog/jaffle-shop"
